Write graphite guide in realtime section
apache/jmeter pull request #699
Opened 2022-02-21 04:36 UTC by shblue21

## Description

Write graphite setting guide docuementation in realtime section, with simple pickle protocol

## Motivation and Context

Improved accessibility for Jmeter and Graphite integration

## How Has This Been Tested?

After building with gradle site, check the screen by resolution.

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/25363091/154889768-1309f0c0-54b4-4fff-b3fe-ee37bebdf4a3.png)

## Types of changes

- Write docs

## Checklist:

- [x] My code follows the [code style][style-guide] of this project.
- [x] I have updated the documentation accordingly.

[style-guide]: https://wiki.apache.org/jmeter/CodeStyleGuidelines

2022-02-21 12:19 UTC, pmouawad commented on xdocs/usermanual/realtime-results.xml
> +    <p><a href="./component_reference.html#Backend_Listener">GraphiteBackendListenerClient</a> section will help you confiugration.</p>
will help you do the configuration

2022-02-21 12:19 UTC, pmouawad commented on xdocs/usermanual/realtime-results.xml
> +<subsection name="&sect-num;.5.1 Graphite Sender" anchor="graphite_sendor">
Remove "Can use"

2022-02-21 12:20 UTC, pmouawad requested changes
Thank you for your PR.
Can you fix the typos so that I can merge it ?
Regards

2022-02-21 17:08 UTC, shblue21 commented
Thanks for the feedback. I am happy to be able to contribute in this way. jmeter is a great tool.

2022-02-22 17:25 UTC, pmouawad approved these changes

2022-03-05 19:58 UTC, closed without merging

2022-03-05 20:00 UTC, FSchumacher commented
Thanks for the PR. I rephrased the wording a bit and removed space at the end of line.